apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.111.0
    chart: opentelemetry-collector
    helm:
      valueFiles:
        - $ArgoCD/monitoring/opentelemetry/collector_values.yaml
  - repoURL: https://github.com/nivav1/ArgoCD.git
    targetRevision: main
    ref: ArgoCD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
