receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-collector.monitoring.svc.cluster.local:4317"
      http:
        endpoint: "otel-collector.monitoring.svc.cluster.local:4318"

exporters:
  prometheus:
    endpoint: "http://localhost:9464"
  logging:
    loglevel: debug
  jaeger:
    endpoint: "http://localhost:14250"

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, jaeger]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
image:
  repository: "otel/opentelemetry-collector-k8s"
mode: "daemonset"
