apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  ports:
    - port: 4317
      name: grpc
    - port: 4318
      name: http
    - port: 9464
      name: prometheus-metrics
    - port: 14250
      name: jeager-traces
  selector:
    app: otel-collector
