apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp
spec:
  selector:
    matchLabels:
      app: website
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: website
        tier: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z db-service 5432; do
                echo "Waiting for database...";
                sleep 5;
              done;
      containers:
      - name: backend
        image: nivav123/backend:v1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
