apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  argocd.argoproj.io/hook: PreSync
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data

