apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 26.0.1
    helm:
      valueFiles:
        - $ArgoCD/monitoring/prometheus/prometheus-values.yaml
  - repoURL: https://github.com/nivav1/ArgoCD.git
    targetRevision: main
    ref: ArgoCD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
