apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      nodePort: 30213
      name: webui
  selector:
    app: prometheus
  type: NodePort
