global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'argocd'
    static_configs:
      - targets: ['argocd-server-metrics.argocd.svc.cluster.local:8083']

  - job_name: 'otel-collector
    static_configs:
      - targets: ["otel-collector.webapp.svc.cluster.local:9464"]
